export const teams = 
    [
        { 
        name: "Andriy",
        surName: "Samaryn",
        position: "Team-lead",
        git: "https://github.com/STIg89",
        linkedin: "https://www.linkedin.com/in/andriy-samarin/",
        description: ["Building the project architecture, developing the project backend"],
        avatar: require('../../../../images/team/Samaryn.jpg'),
        },
        { 
        name: "Halina",
        surName: "Kilbovych",
        position: "Scrum-master",
        git: "https://github.com/HalynaKilbovych",
        linkedin: "https://www.linkedin.com/in/halyna-kilbovych/",
        description: ["Organization of teamwork, development of the start page, 404 pages and autologin"],
        avatar: require('../../../../images/team/Kilbovych.jpg'),
       },
       { 
        name: "Iryna",
        surName: "Grytsaenko",
        position: "Developer",
        git: "https://github.com/Iryna-Gry",
        linkedin: "https://www.linkedin.com/in/iryna-grytsaenko/",
        description: ["Calendar development"],
        avatar: require('../../../../images/team/Grytsaenko.jpg'),
       },
       { 
        name: "Victoria",
        surName: "Bilauchuk",
        position: "Developer",
        git: "https://github.com/VictoriaBil",
        linkedin: "https://www.linkedin.com/in/victoria-bilauchuk-187442154",
        description: ["Development of a user registration block, visual theme change"],
        avatar: require('../../../../images/team/Bilauchuk.jpg'),
       },
       { 
        name: "Svitlana",
        surName: "Losieva",
        position: "Developer",
        git: "https://github.com/atevsl",
        linkedin: "https://www.linkedin.com/in/svitlana-losieva/",
        description: ["Calendar and tasks development"],
        avatar: require('../../../../images/team/Losieva.jpg'),
       },
       { 
        name: "Iryna",
        surName: "Zaitseva",
        position: "Developer",
        git: "https://github.com/izaitseva",
        linkedin: "https://www.linkedin.com/in/iryna-zaitseva/",
        description: ["Development of sidebar and header modules"],
        avatar: require('../../../../images/team/Zaitseva.jpg'),
       },
       { 
        name: "Kateryna",
        surName: "Vabishchevich",
        position: "Developer",
        git: "https://github.com/Kate-Vabishchevich",
        linkedin: "https://www.linkedin.com/in/kateryna-vabishchevich/",
        description:[ "LoginPage development and site language change"],
        avatar: require('../../../../images/team/Vabishchevich.jpg'),
       },
       { 
        name: "Alona",
        surName: "Panchenko",
        position: "Developer",
        git: "https://github.com/Enotishche",
        linkedin: "https://www.linkedin.com/in/alona-panchenko-17477a26b/",
        description: ["Development of a slider with reviews and a modal window with information about the team"],
        avatar: require('../../../../images/team/Panchenko.jpg'),
       },
       { 
        name: "Oleksandr",
        surName: "Chernomorets",
        position: "Developer",
        git: "https://github.com/AlexanderChernomorets",
        linkedin: "https://www.linkedin.com/",
        description:[ "Development of a modal window with reviews"],
        avatar: require('../../../../images/team/Chernomorets.jpg'),
       },
       { 
        name: "Alexey",
        surName: "Alexeev",
        position: "Developer",
        git: "https://github.com/Lelikboss",
        linkedin: "https://www.linkedin.com/in/alexeyalexeevworkpage/",
        description: ["Development of the backend of registration blocks and tasks. Swagger"],
        avatar: require('../../../../images/team/Alexeev.jpg'),
       },
       { 
        name: "Andrii",
        surName: "Kostenko",
        position: "Developer",
        git: "https://github.com/Andruha0013",
        linkedin: "https://www.linkedin.com/",
        description: ["Development of the backend of login, reviews and avatar"],
        avatar: require('../../../../images/team/Kostenko.jpg'),
       },
       { 
        name: "Karyna",
        surName: "Borysenko",
        position: "Developer",
        git: "https://github.com/Karyna-Borysenko",
        linkedin: "https://www.linkedin.com/in/karyna-borysenko/",
        description: ["Development of User Profile"],
        avatar: require('../../../../images/team/Borysenko.jpg'),
       },
       { 
        name: "Viktor",
        surName: "Solomianiy",
        position: "Developer",
        git: "https://github.com/ViktorSolomianiy",
        linkedin: "https://www.linkedin.com/in/viktor-solomianiy/",
        description: ["Development Calendar Page, modal and Tasks"],
        avatar: require('../../../../images/team/Solomianiy.jpg'),
       },
    ];
 